Use stderr instead of a file.

diff --git a/bash-ini-parser b/bash-ini-parser
--- a/bash-ini-parser
+++ b/bash-ini-parser
@@ -82,7 +82,7 @@ function cfg_writer {
       fun="$(declare -F $PREFIX$SECTION)"
       if [ -z "$fun" ]
       then
-         echo "section $SECTION not found" >2
+         echo "section $SECTION not found" 1>&2
          exit 1
       fi
    fi
@@ -130,7 +130,7 @@ function cfg_unset {
       fun="$(declare -F $PREFIX$SECTION)"
       if [ -z "$fun" ]
       then
-         echo "section $SECTION not found" >2
+         echo "section $SECTION not found" 1>&2
          return
       fi
    fi
@@ -168,7 +168,7 @@ function cfg_clear {
       fun="$(declare -F $PREFIX$SECTION)"
       if [ -z "$fun" ]
       then
-         echo "section $SECTION not found" >2
+         echo "section $SECTION not found" 1>&2
          exit 1
       fi
    fi
@@ -188,7 +188,7 @@ function cfg_update {
    fun="$(declare -F $PREFIX$SECTION)"
    if [ -z "$fun" ]
    then
-      echo "section $SECTION not found" >2
+      echo "section $SECTION not found" 1>&2
       exit 1
    fi
    fun="${fun//declare -f/}"
